version: "3.8"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      # Lägg dessa i Coolify (per nod)
      # - SUPABASE_URL=...
      # - SUPABASE_SERVICE_ROLE_KEY=...
      # - INTERNAL_API_KEY=...
      # - BREVO_API_KEY=...
      # - FROM_EMAIL=...
      # - FROM_NAME=...
      # - PYTHONUNBUFFERED=1
      # - TZ=Europe/Stockholm
    ports:
      - "9100:8000"   # <- publik host-port på noden
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost:8000/docs || exit 1"]
      start_period: 20s
      interval: 10s
      timeout: 3s
      retries: 5

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_SUPABASE_URL: ${NEXT_PUBLIC_SUPABASE_URL}
        NEXT_PUBLIC_SUPABASE_ANON_KEY: ${NEXT_PUBLIC_SUPABASE_ANON_KEY}
        NEXT_PUBLIC_API_BASE_URL: ${NEXT_PUBLIC_API_BASE_URL}
    restart: unless-stopped
    depends_on:
      backend:
        condition: service_healthy
    environment:
      NEXT_PUBLIC_SUPABASE_URL: ${NEXT_PUBLIC_SUPABASE_URL}
      NEXT_PUBLIC_SUPABASE_ANON_KEY: ${NEXT_PUBLIC_SUPABASE_ANON_KEY}
      NEXT_PUBLIC_API_BASE_URL: ${NEXT_PUBLIC_API_BASE_URL}
    ports:
      - "3010:3000"   # <- publik host-port på noden
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost:3000/ || exit 1"]
      start_period: 30s
      interval: 10s
      timeout: 3s
      retries: 5
