export const ENODE_EVENT_LABELS: Record<string, string> = {
    "user:vehicle:discovered": "Vehicle linked",
    "user:vehicle:updated": "Vehicle updated",
    "user:vehicle:deleted": "Vehicle unlinked",
    "user:vehicle:smart-charging-status-updated": "Smart charging updated",
    "user:charge-action:updated": "Charge action updated",
    "user:vendor-action:updated": "Vendor action updated",
    "user:schedule:execution-updated": "Schedule execution updated",
    "user:charger:discovered": "Charger linked",
    "user:charger:updated": "Charger updated",
    "user:charger:deleted": "Charger unlinked",
    "user:hvac:discovered": "HVAC linked",
    "user:hvac:updated": "HVAC updated",
    "user:hvac:deleted": "HVAC unlinked",
    "user:inverter:discovered": "Inverter linked",
    "user:inverter:updated": "Inverter updated",
    "user:inverter:deleted": "Inverter unlinked",
    "user:inverter:statistics-updated": "Inverter statistics updated",
    "user:credentials:invalidated": "Credentials invalidated",
    "user:battery:discovered": "Battery linked",
    "user:battery:updated": "Battery updated",
    "user:battery:deleted": "Battery unlinked",
    "user:meter:discovered": "Meter linked",
    "user:meter:updated": "Meter updated",
    "user:meter:deleted": "Meter unlinked",
    "enode:webhook:test": "Webhook test",
    "system:heartbeat": "Heartbeat",
  }
  