# backend/app/main.py

from fastapi import FastAPI
from app.api import me, status
from app.config import SUPABASE_URL, SUPABASE_ANON_KEY, SUPABASE_SERVICE_ROLE_KEY, SUPABASE_JWT_SECRET

app = FastAPI(
    title="EVLink Backend",
    version="0.1.0",
    description="Minimal FastAPI backend for secured API access.",
)

# Include only public (unauthenticated) endpoints for now
app.include_router(status.router)
app.include_router(me.router)



# eyJhbGciOiJIUzI1NiIsImtpZCI6InVodVF6YW0ySFpXYk5RRTgiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3hpcGNnemJzem5sY3F3eWd3bnJnLnN1cGFiYXNlLmNvL2F1dGgvdjEiLCJzdWIiOiI2NzEwNDNlYS05NTVjLTRmNTctYWJhNS00YzcxYTAzNDg0MTIiLCJhdWQiOiJhdXRoZW50aWNhdGVkIiwiZXhwIjoxNzQ2MzA4MDQ3LCJpYXQiOjE3NDYzMDQ0NDcsImVtYWlsIjoicm9nZXIuYXNwZWxpbkBob3RtYWlsLnNlIiwicGhvbmUiOiIiLCJhcHBfbWV0YWRhdGEiOnsicHJvdmlkZXIiOiJnaXRodWIiLCJwcm92aWRlcnMiOlsiZ2l0aHViIl19LCJ1c2VyX21ldGFkYXRhIjp7ImF2YXRhcl91cmwiOiJodHRwczovL2F2YXRhcnMuZ2l0aHVidXNlcmNvbnRlbnQuY29tL3UvOTQ2NzMxND92PTQiLCJlbWFpbCI6InJvZ2VyLmFzcGVsaW5AaG90bWFpbC5zZSIsImVtYWlsX3ZlcmlmaWVkIjp0cnVlLCJmdWxsX25hbWUiOiJSb2dlciBBc3BlbGluIiwiaXNzIjoiaHR0cHM6Ly9hcGkuZ2l0aHViLmNvbSIsIm5hbWUiOiJSb2dlciBBc3BlbGluIiwicGhvbmVfdmVyaWZpZWQiOmZhbHNlLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJyb2dhc3AiLCJwcm92aWRlcl9pZCI6Ijk0NjczMTQiLCJyb2xlIjoiYWRtaW4iLCJzdWIiOiI5NDY3MzE0IiwidXNlcl9uYW1lIjoicm9nYXNwIn0sInJvbGUiOiJhdXRoZW50aWNhdGVkIiwiYWFsIjoiYWFsMSIsImFtciI6W3sibWV0aG9kIjoib2F1dGgiLCJ0aW1lc3RhbXAiOjE3NDYzMDQ0NDd9XSwic2Vzc2lvbl9pZCI6IjE4NTBiOTZkLWY3MTgtNGFkOC1iYzcyLWNjZTdmZmZiOTk4NCIsImlzX2Fub255bW91cyI6ZmFsc2V9.65NXRUPST9tjr2tos4slYR8R76gMQsJD1zx4sorpG5s